### ISSUE TITLE
Segmentation fault on empty "--from" or "--to"

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/lookout#145]
If I call `./lookout review --from ""` the program crashes:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa8f1a0]

goroutine 1 [running]:
github.com/src-d/lookout/vendor/gopkg.in/src-d/go-git%2ev4.(*Repository).ResolveRevision(0xc420a76450, 0x7fffcbdb8a04, 0x0, 0xc420a76450, 0xc4201c9ad8, 0xa8a8a2)
	/home/travis/gopath/src/github.com/src-d/lookout/vendor/gopkg.in/src-d/go-git.v4/repository.go:1131 +0xf20
main.getCommitHashByRev(0xc420a76450, 0x7fffcbdb8a04, 0x0, 0x0, 0xc420a347e0, 0xc420a706c0, 0xc420a76420)
	/home/travis/gopath/src/github.com/src-d/lookout/cmd/lookout/event.go:158 +0x43
main.(*EventCommand).resolveRefs(0xc4200bd760, 0x0, 0x0, 0x3, 0xc4201c9ca8)
	/home/travis/gopath/src/github.com/src-d/lookout/cmd/lookout/event.go:49 +0x5c
main.(*ReviewCommand).Execute(0xc4200bd760, 0xc420a6d420, 0x0, 0x7, 0xc4200bd760, 0xabba01)
	/home/travis/gopath/src/github.com/src-d/lookout/cmd/lookout/review.go:31 +0x69
github.com/src-d/lookout/util/cli.New.func1(0x7fc91ff7b140, 0xc4200bd760, 0xc420a6d420, 0x0, 0x7, 0x1, 0x0)
	/home/travis/gopath/src/github.com/src-d/lookout/util/cli/app.go:24 +0x93
github.com/src-d/lookout/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc420a34660, 0xc420030090, 0x7, 0x7, 0x7, 0xf0f5ae, 0x18, 0x0, 0x0)
	/home/travis/gopath/src/github.com/src-d/lookout/vendor/github.com/jessevdk/go-flags/parser.go:314 +0x7c7
github.com/src-d/lookout/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(0xc420a34660, 0x0, 0x0, 0xc4201c9f78, 0x0, 0x0)
	/home/travis/gopath/src/github.com/src-d/lookout/vendor/github.com/jessevdk/go-flags/parser.go:186 +0x71
github.com/src-d/lookout/util/cli.(*App).RunMain(0xc42049b440)
	/home/travis/gopath/src/github.com/src-d/lookout/util/cli/app.go:32 +0x32
main.main()
	/home/travis/gopath/src/github.com/src-d/lookout/cmd/lookout/main.go:14 +0x2d
```

**Comment by bzz** [comment]
🤦‍♂️ And thank you for reporting!
