### ISSUE TITLE
lookout-sdk hangs if bblfsh failed to parse the file

### ISSUE THREAD

**Issue by zurk** [src-d/lookout#404]
How to reproduce:
```bash

# run bblfsh
docker run -d --rm --name style_analyzer_bblfshd --privileged -p 9432\:9432 bblfsh/bblfshd:v2.10.0
docker exec style_analyzer_bblfshd bblfshctl driver install javascript docker://bblfsh/javascript-driver\:v2.5.0

# run format analyzer
git clone https://github.com/src-d/style-analyzer
cd style-analyzer
pip3 install .
python3 -m lookout run lookout.style.format -s 0.0.0.0:2000 --db sqlite:///db.sqlite3 --fs ./tmp --log-level DEBUG
```
and in another terminal
```bash
git clone https://github.com/vuejs/vue
# download latest lookout-sdk v0.6.0
./lookout-sdk review --git-dir=./vue --log-level=DEBUG ipv4://localhost:2000 --to=b7105ae8c9093e36ec89a470caa3b78bda3ef467 --from=db1d0474997e9e60b8b0d39a3b7c2af55cfd0d4a
```

It runs aroud 2-3 mins and when it hangs you get next output from style analyzer:
```
INFO:ce20:FormatAnalyzer:train file:///Users/k/example-delme/vue db1d0474997e9e60b8b0d39a3b7c2af55cfd0d4a {}
ERROR:c57d:grpc._common:Exception deserializing message!
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/grpc/_common.py", line 87, in _transform
    return transformer(message)
google.protobuf.message.DecodeError: Error parsing message
ERROR:ce20:EventListener:FAIL ?
Traceback (most recent call last):
  File "/Users/k/sourced/workdir/lookout-sdk-ml/lookout/core/event_listener.py", line 181, in wrapped_catch_them_all
    return func(self, request, context)
  File "/Users/k/sourced/workdir/lookout-sdk-ml/lookout/core/event_listener.py", line 202, in wrapped_handle
    return getattr(self.handlers, method_name)(request)
  File "/Users/k/sourced/workdir/lookout-sdk-ml/lookout/core/manager.py", line 75, in process_review_event
    model = analyzer.train(base_ptr, mycfg, self._data_service)
  File "/Users/k/sourced/workdir/lookout-sdk-ml/lookout/core/data_requests.py", line 152, in wrapped_with_uasts_and_contents
    return func(cls, ptr, config, data_service, files=files, **data)
  File "/Users/k/sourced/workdir/style-analyzer/lookout/style/format/analyzer.py", line 155, in train
    for language, files in files_by_language(data["files"]).items():
  File "/Users/k/sourced/workdir/lookout-sdk-ml/lookout/core/lib.py", line 88, in files_by_language
    for file in files:
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 345, in __next__
    return self._next()
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 328, in _next
    raise self
  File "/Users/k/sourced/workdir/lookout-sdk-ml/lookout/core/lib.py", line 83, in files_by_language
    for file in files:
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 345, in __next__
    return self._next()
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 339, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Exception deserializing response!"
	debug_error_string = "None"
>

```

and from lookout-sdk:
```
[2018-12-09T17:02:00.290871+01:00]  INFO streaming client call finished app=lookout-sdk duration=36.25301549s error=rpc error: code = Internal desc = <class 'grpc._channel._Rendezvous'>: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Exception deserializing response!"
	debug_error_string = "None"
> grpc.code=Internal grpc.method=NotifyReviewEvent grpc.service=pb.Analyzer grpc.start_time=2018-12-09T17:01:24+01:00 source=grpchelper/logger.go:19 span.kind=client system=grpc
[2018-12-09T17:02:00.290967+01:00] ERROR analysis failed analyzer=test-analyzes app=lookout-sdk error=rpc error: code = Internal desc = <class 'grpc._channel._Rendezvous'>: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Exception deserializing response!"
	debug_error_string = "None"
> provider= source=server/server.go:281
[2018-12-09T17:02:00.291035+01:00]  INFO status: success app=lookout-sdk source=server/server.go:426
[2018-12-09T17:02:00.321961+01:00]  INFO streaming client call finished app=lookout-sdk duration=34.416307ms grpc.code=OK grpc.method=Parse grpc.service=gopkg.in.bblfsh.sdk.v1.protocol.ProtocolService grpc.start_time=2018-12-09T17:02:00+01:00 source=grpchelper/logger.go:19 span.kind=client system=grpc
[2018-12-09T17:02:00.323186+01:00] DEBUG parsing uast for file: test/helpers/test-object-option.js app=lookout-sdk source=bblfsh/bblfsh.go:109
[2018-12-09T17:02:00.323262+01:00]  INFO unary client call started app=lookout-sdk grpc.method=Parse grpc.service=gopkg.in.bblfsh.sdk.v1.protocol.ProtocolService source=grpchelper/logger.go:19 span.kind=client system=grpc
[2018-12-09T17:02:00.344998+01:00]  INFO streaming client call finished app=lookout-sdk duration=21.74224ms grpc.code=OK grpc.method=Parse grpc.service=gopkg.in.bblfsh.sdk.v1.protocol.ProtocolService grpc.start_time=2018-12-09T17:02:00+01:00 source=grpchelper/logger.go:19 span.kind=client system=grpc
[2018-12-09T17:02:00.346075+01:00] DEBUG parsing uast for file: test/helpers/to-equal.js app=lookout-sdk source=bblfsh/bblfsh.go:109
[2018-12-09T17:02:00.346136+01:00]  INFO unary client call started app=lookout-sdk grpc.method=Parse grpc.service=gopkg.in.bblfsh.sdk.v1.protocol.ProtocolService source=grpchelper/logger.go:19 span.kind=client system=grpc
[2018-12-09T17:02:00.372475+01:00]  INFO streaming client call finished app=lookout-sdk duration=26.332366ms grpc.code=OK grpc.method=Parse grpc.service=gopkg.in.bblfsh.sdk.v1.protocol.ProtocolService grpc.start_time=2018-12-09T17:02:00+01:00 source=grpchelper/logger.go:19 span.kind=client system=grpc
[2018-12-09T17:02:00.373505+01:00] DEBUG parsing uast for file: test/helpers/to-have-been-warned.js app=lookout-sdk source=bblfsh/bblfsh.go:109
[2018-12-09T17:02:00.373577+01:00]  INFO unary client call started app=lookout-sdk grpc.method=Parse grpc.service=gopkg.in.bblfsh.sdk.v1.protocol.ProtocolService source=grpchelper/logger.go:19 span.kind=client system=grpc
<...>
```
And there is no logs about style-analyzer failure, however we report it in `log_exceptions` wrapper as usual: 

https://github.com/zurk/lookout-sdk-ml/blob/bbd7a90d00f7d6ce2412883e9c4ae1f1f5730d23/lookout/core/event_listener.py#L189 

FYI, Bblfsh looks to hit this issue https://github.com/bblfsh/client-python/issues/89.

**Comment by smacker** [comment]
Hi @zurk ! I'm not sure I it's problem in lookout. From the logs I see only your style-analyzer fails due to the limitation in bblfsh uast1 and python client. Afaik the only way to fix it - switch to uast2.

Example of your command with dummy analyzer:
```
$ go run cmd/lookout-sdk/*.go review --git-dir=/Users/smacker/tmp/vue --log-level=DEBUG ipv4://localhost:9930 --to=b7105ae8c9093e36ec89a47
...
[2018-12-10T10:45:50.827749+01:00]  INFO line comment app=lookout-sdk file=types/vue.d.ts line=98 source=server/server.go:417 text=This line exceeded 120 chars.
[2018-12-10T10:45:50.827884+01:00]  INFO status: success app=lookout-sdk source=server/server.go:426
```

In your case style-analyzer failed to deserialize protobuf and can't write to grpc channel anymore.
sdk binary waits for your analyzer to reply but never receives an answer.

With real lookoutd we have timeouts for such case. But sdk bin supposed to be used only for testing where you control what's going on and can stop it by yourself pressing ctrl-c.

You need to make sure you close the channel in case of error correctly. We handle it properly:
```
[2018-12-10T10:55:27.086008+01:00]  INFO streaming client call finished app=lookout-sdk duration=1.047045058s error=rpc error: code = Unavailable desc = transport is closing grpc.code=Unavailable grpc.method=NotifyReviewEvent grpc.service=pb.Analyzer grpc.start_time=2018-12-10T10:55:26+01:00 source=grpchelper/logger.go:19 span.kind=client system=grpc
[2018-12-10T10:55:27.086294+01:00] ERROR analysis failed analyzer=test-analyzes app=lookout-sdk error=rpc error: code = Unavailable desc = transport is closing provider= source=server/server.go:281
[2018-12-10T10:55:27.086374+01:00]  INFO status: success app=lookout-sdk source=server/server.go:426
[2018-12-10T10:55:27.167792+01:00]  INFO streaming server call finished app=lookout-sdk duration=127.365282ms error=request canceled: context canceled grpc.code=Unknown grpc.method=GetChanges grpc.service=pb.Data grpc.start_time=2018-12-10T10:55:27+01:00 source=grpchelper/logger.go:19 span.kind=server system=grpc
```

**Comment by zurk** [comment]
Yeah, I see. @smacker thanks for the explanation and investigation.

@smola is it possible to move this issue to https://github.com/src-d/style-analyzer?

**Comment by vmarkovtsev** [comment]
@zurk This is trivial, we raise an exception in abort() while we should report the error code and not explode instead. Try with https://github.com/src-d/lookout-sdk-ml/pull/20

**Comment by vmarkovtsev** [comment]
@zurk can be closed
