### ISSUE TITLE
Panic on ChangesRequest

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/lookout#91]
I am sending the following `ChangesRequest` to `./lookout review ipv4://localhost:2000`:

```
base {
  internal_repository_url: "file:///home/vadim/Projects/style-analyzer/lookout/core"
  hash: "e2ca665f6f45a3e9c44b3e1c6bee07c236efc842"
}
head {
  internal_repository_url: "file:///home/vadim/Projects/style-analyzer/lookout/core"
  hash: "b6365d0cdf4a2eb1b389960ac8f437a9b3cd1cf7"
}
exclude_vendored: true
want_uast: true
```
(want_content is false, not shown in the text for some reason).

and get:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xac0082]

goroutine 70 [running]:
github.com/src-d/lookout/service/git.filterVendor(0x0, 0x0, 0x0, 0xc4202c46e0)
	/home/travis/gopath/src/github.com/src-d/lookout/service/git/scanner.go:299 +0x22
github.com/src-d/lookout/service/git.NewChangeExcludeVendorScanner.func1(0xc42026cc20, 0xc42026cc20, 0xc420c636ca, 0xc420c6c000)
	/home/travis/gopath/src/github.com/src-d/lookout/service/git/scanner.go:305 +0x2f
github.com/src-d/lookout.(*FnChangeScanner).Next(0xc4200c16c0, 0xc420be8b00)
	/home/travis/gopath/src/github.com/src-d/lookout/data.go:288 +0x99
github.com/src-d/lookout.(*FnChangeScanner).Next(0xc4200c1800, 0xc420af0d00)
	/home/travis/gopath/src/github.com/src-d/lookout/data.go:286 +0x5a
github.com/src-d/lookout/service/bblfsh.(*ChangeScanner).Next(0xc42025a6e0, 0xc420af0da0)
	/home/travis/gopath/src/github.com/src-d/lookout/service/bblfsh/bblfsh.go:146 +0x45
github.com/src-d/lookout.(*DataServerHandler).GetChanges(0xc42000cce0, 0xc4200c0300, 0xfa8120, 0xc4201e0fe0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/src-d/lookout/data.go:86 +0x151
github.com/src-d/lookout/pb._Data_GetChanges_Handler(0xc54de0, 0xc42000cce0, 0xfa7340, 0xc4200dee70, 0x17c8060, 0xc420a18720)
	/home/travis/gopath/src/github.com/src-d/lookout/pb/service_data.pb.go:189 +0x10e
github.com/src-d/lookout/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc4200f4380, 0xfa9200, 0xc420a24200, 0xc42022e100, 0xc420abc3c0, 0x179adc0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/src-d/lookout/vendor/google.golang.org/grpc/server.go:1160 +0xa2d
github.com/src-d/lookout/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200f4380, 0xfa9200, 0xc420a24200, 0xc42022e100, 0x0)
	/home/travis/gopath/src/github.com/src-d/lookout/vendor/google.golang.org/grpc/server.go:1253 +0x12b1
github.com/src-d/lookout/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4200b8120, 0xc4200f4380, 0xfa9200, 0xc420a24200, 0xc42022e100)
	/home/travis/gopath/src/github.com/src-d/lookout/vendor/google.golang.org/grpc/server.go:680 +0x9f
created by github.com/src-d/lookout/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/travis/gopath/src/github.com/src-d/lookout/vendor/google.golang.org/grpc/server.go:678 +0xa1
```

**Comment by vmarkovtsev** [comment]
```
git diff HEAD^...HEAD --stat
 lookout/__init__.py                     |   1 +
 lookout/__main__.py                     |  20 ++++++++++++++++++
 lookout/core/analyzer_model.py          |   3 ++-
 lookout/core/cmdline.py                 | 140 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 lookout/core/data_requests.py           |   3 +--
 lookout/core/event_listener.py          |   5 +++++
 lookout/core/main.py                    |   0
 lookout/core/manager.py                 |   7 +++++--
 lookout/core/sqla_model_repository.py   |  32 +++++++++++++++++++++-------
 lookout/style/__init__.py               |   2 +-
 lookout/style/__main__.py               |   9 --------
 lookout/style/format/__init__.py        |  51 ++------------------------------------------
 lookout/style/format/format_analyzer.py |  54 +++++++++++++++++++++++++++++++++++++++++++++++
 requirements.txt                        |   5 ++++-
 setup.py                                |   9 +++++---
 15 files changed, 266 insertions(+), 75 deletions(-)
```
